<?php
/**
 * Copyright (c) 2014 - 2015, Designmoves (http://www.designmoves.nl)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Designmoves nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DesignmovesDeviceContext\Module'                                                 => __DIR__ . '/Module.php',
  'DesignmovesDeviceContext\Controller\Plugin\DeviceContext'                        => __DIR__ . '/src/DesignmovesDeviceContext/Controller/Plugin/DeviceContext.php',
  'DesignmovesDeviceContext\Factory\Controller\Plugin\DeviceContextFactory'         => __DIR__ . '/src/DesignmovesDeviceContext/Factory/Controller/Plugin/DeviceContextFactory.php',
  'DesignmovesDeviceContext\Factory\Listener\LayoutListenerFactory'                 => __DIR__ . '/src/DesignmovesDeviceContext/Factory/Listener/LayoutListenerFactory.php',
  'DesignmovesDeviceContext\Factory\Listener\TemplateListenerFactory'               => __DIR__ . '/src/DesignmovesDeviceContext/Factory/Listener/TemplateListenerFactory.php',
  'DesignmovesDeviceContext\Factory\Options\ModuleOptionsFactory'                   => __DIR__ . '/src/DesignmovesDeviceContext/Factory/Options/ModuleOptionsFactory.php',
  'DesignmovesDeviceContext\Factory\View\Helper\DeviceContextFactory'               => __DIR__ . '/src/DesignmovesDeviceContext/Factory/View/Helper/DeviceContextFactory.php',
  'DesignmovesDeviceContext\Listener\LayoutListener'                                => __DIR__ . '/src/DesignmovesDeviceContext/Listener/LayoutListener.php',
  'DesignmovesDeviceContext\Listener\TemplateListener'                              => __DIR__ . '/src/DesignmovesDeviceContext/Listener/TemplateListener.php',
  'DesignmovesDeviceContext\Options\MobileOptions'                                  => __DIR__ . '/src/DesignmovesDeviceContext/Options/MobileOptions.php',
  'DesignmovesDeviceContext\Options\ModuleOptions'                                  => __DIR__ . '/src/DesignmovesDeviceContext/Options/ModuleOptions.php',
  'DesignmovesDeviceContext\View\Helper\DeviceContext'                              => __DIR__ . '/src/DesignmovesDeviceContext/View/Helper/DeviceContext.php',
  'DesignmovesDeviceContextTest\Bootstrap'                                          => __DIR__ . '/test/Bootstrap.php',
  'DesignmovesDeviceContextTest\Controller\Plugin\DeviceContextTest'                => __DIR__ . '/test/DesignmovesDeviceContextTest/Controller/Plugin/DeviceContextTest.php',
  'DesignmovesDeviceContextTest\Factory\Controller\Plugin\DeviceContextFactoryTest' => __DIR__ . '/test/DesignmovesDeviceContextTest/Factory/Controller/Plugin/DeviceContextFactoryTest.php',
  'DesignmovesDeviceContextTest\Factory\Listener\LayoutListenerFactoryTest'         => __DIR__ . '/test/DesignmovesDeviceContextTest/Factory/Listener/LayoutListenerFactoryTest.php',
  'DesignmovesDeviceContextTest\Factory\Listener\TemplateListenerFactoryTest'       => __DIR__ . '/test/DesignmovesDeviceContextTest/Factory/Listener/TemplateListenerFactoryTest.php',
  'DesignmovesDeviceContextTest\Factory\Options\ModuleOptionsFactoryTest'           => __DIR__ . '/test/DesignmovesDeviceContextTest/Factory/Options/ModuleOptionsFactoryTest.php',
  'DesignmovesDeviceContextTest\Factory\View\Helper\DeviceContextFactoryTest'       => __DIR__ . '/test/DesignmovesDeviceContextTest/Factory/View/Helper/DeviceContextFactoryTest.php',
  'DesignmovesDeviceContextTest\Listener\LayoutListenerTest'                        => __DIR__ . '/test/DesignmovesDeviceContextTest/Listener/LayoutListenerTest.php',
  'DesignmovesDeviceContextTest\Listener\TemplateListenerTest'                      => __DIR__ . '/test/DesignmovesDeviceContextTest/Listener/TemplateListenerTest.php',
  'DesignmovesDeviceContextTest\ModuleTest'                                         => __DIR__ . '/test/DesignmovesDeviceContextTest/ModuleTest.php',
  'DesignmovesDeviceContextTest\Options\MobileOptionsTest'                          => __DIR__ . '/test/DesignmovesDeviceContextTest/Options/MobileOptionsTest.php',
  'DesignmovesDeviceContextTest\Options\ModuleOptionsTest'                          => __DIR__ . '/test/DesignmovesDeviceContextTest/Options/ModuleOptionsTest.php',
  'DesignmovesDeviceContextTest\View\Helper\DeviceContextTest'                      => __DIR__ . '/test/DesignmovesDeviceContextTest/View/Helper/DeviceContextTest.php',
);
